// <auto-generated />
using System;
using DemoECS.DbStuff;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace demo_ecs.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200329002700_ChangingToPersistence")]
    partial class ChangingToPersistence
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DemoECS.Component.Cord", b =>
                {
                    b.Property<int>("CordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("PersistenceId")
                        .HasColumnType("integer");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("CordId");

                    b.HasIndex("PersistenceId");

                    b.ToTable("Cords");
                });

            modelBuilder.Entity("DemoECS.Component.Identity", b =>
                {
                    b.Property<int>("IdentityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("PersistenceId")
                        .HasColumnType("integer");

                    b.HasKey("IdentityId");

                    b.HasIndex("PersistenceId");

                    b.ToTable("Identities");
                });

            modelBuilder.Entity("DemoECS.Component.Persistence", b =>
                {
                    b.Property<int>("PersistenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.HasKey("PersistenceId");

                    b.ToTable("Persistences");
                });

            modelBuilder.Entity("DemoECS.Component.Cord", b =>
                {
                    b.HasOne("DemoECS.Component.Persistence", "Persistence")
                        .WithMany()
                        .HasForeignKey("PersistenceId");
                });

            modelBuilder.Entity("DemoECS.Component.Identity", b =>
                {
                    b.HasOne("DemoECS.Component.Persistence", "Persistence")
                        .WithMany()
                        .HasForeignKey("PersistenceId");
                });
#pragma warning restore 612, 618
        }
    }
}
